version: '3.6'
services:
  api: 
    container_name: api
    build: ./api
    ports: 
      - "3000:3000"
    volumes:
      - ./api:/app
    depends_on: 
      - mongo
    env_file:
      - .env
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    depends_on:
      - mongo_import
  mongo_import:
    container_name: mongo_import
    image: mongo
    volumes:
      - ./data:/data
    command: /data/import.sh
  
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - '8080:8080'
    environment:
      API_URL: $URL_SWAGGER
    


