version: '3.6'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  api: 
    container_name: api
    build: ./api
    ports: 
      - "3000:3000"
    volumes:
      - ./api:/app
    depends_on: 
      - mongo
    env_file:
      - .env


